apiVersion : apps/v1
kind: Deployment
metadata:
  name: front
  labels:
    app : front
spec:
  selector:
    matchLabels:
      project: front
  template:
    metadata:
      labels:
        project: front   # Service will look for those PODS Labels!!!
    spec:
      containers:
        - name : teachfront
          image: us.gcr.io/gcp101233-lv61301devops/app-images/teach_front-image:0.9
          ports:
            - containerPort: 3000

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: my-autoscaling-front
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta1v1
    kind: Deployment
    name: front
  minReplicas: 3
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 80

---
apiVersion: v1
kind: Service
metadata:
  name: teach-ua-front
  labels:
     app: prod-front
spec:
  selector:
    project: front      # Selecting PODs with those Labels
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 80  # Port on Load Balancer
      targetPort: 3000  # Port on Pod
  type: LoadBalancer
